### ISSUE TITLE
Security: Specify AKS Memory and CPU Quotas

### ISSUE THREAD

**Issue by guypritchard** [buerokratt/Cross-functional-requirements#82]
As per the [Security Architecture](https://github.com/buerokratt/Cross-functional-requirements/blob/main/docs/technical/security.md)

Apply some 'sensible' defaults for resource limits:

```yaml
...
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
...
```

### Acceptance Criteria
- [ ] Determine Resource Limits and apply to CentOps
- [ ] Determine Resource Limits and apply to .NET DMR
- [ ] Determine Resource Limits and apply to MockBot
- [ ] Determine Resource Limits and apply to MockClassifier
